### ISSUE TITLE
Vector tile to-do list

### ISSUE THREAD

**Issue by twpayne** [openlayers/ol3#1911]
#1744 adds initial support for vector tiles, but some functionality is missing:

- [ ] Expiration of cached vector tiles in `ol.source.TileVector`
- [ ] Prioritisation of vector tile loading
- [ ] Use of interim vector tiles while waiting for higher/lower zoom level tiles to load

All of these are implemented for raster tiles, but not for vector tiles.

Note that the use of interim times is trickier for vector tiles, since you cannot rely on pixel  overwriting (as is used for opaque raster layers), nor can you clear the relevant part of the output canvas before drawing (as is used for transparent raster layers) (at least not without making modifications to the vector layer renderer).

There are a number of possible strategies, including:
- only using interim tiles if none of the corresponding actual-zoom-level tiles are loaded (this will lead to blank areas on the map once tiles start loading)
- using interim tiles only until all the actual-zoom-level tiles are loaded (this will lead to lower resolution data being displayed for longer)
- clipping out the parts of the interim tile where actual-zoom-level tiles are available (CPU intensive, and quite delicate to implement)

Note that the new version Google Maps uses low resolution raster tiles when vector tiles are not yet loaded. Incidentally, this interim tile problem is also why most vector tile demos look much better when you zoom in than when you zoom out!
