### ISSUE TITLE
Move dependencies out of repo

### ISSUE THREAD

**Issue by tschaub** [openlayers/ol3#2270]
Wherever possible, we should add dependencies to `package.json` instead of copying them into the repository (since `npm install` is a required setup step).  We should be able to remove the following:

 - [x] `resources/bootstrap`
 - [x] `examples/jquery.min.js`
 - [ ] `examples/Jugl.js`
 - [x] `test/expect-0.2.0-ol3` (see #2312)
 - [x] `test/jquery-1.9.1` (see #2312)
 - [x] `test/mocha-1.8.1` (see #2312)
 - [x] `test/mocha-phantomjs` (see #2312)
 - [x] `test/sinon-1.6.0` (see #2312)
 - [x] `test/mocha-phantomjs.coffee` (see #2312)
 - [x] `test/mocha-phantomjs.js` (see #2312)

**Comment by tschaub** [comment]
Closing this as good enough for now.
